=== kalkulacka-one/volebni-kalkulacka-2022/data/schemas/election.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://www.volebnikalkulacka.cz/data/schemas/election.schema.json",
  "title": "Election",
  "description": "Election provides various details about an election such as districts and rounds",
  "type": "object",
  "$defs": {
    "id": {
      "title": "ID",
      "description": "Unique identifier of an election in the format of UUID",
      "type": "string",
      "format": "uuid",
      "examples": ["ad9b73fc-e578-4b3a-9623-533d76224cbc"]
    },
    "key": {
      "title": "Key",
      "description": "Human-friendly unique key of an election in the hyphen-separated lowercased format",
      "type": "string",
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$",
      "examples": ["prezidentske-2023"]
    },
    "createdAt": {
      "title": "Created at",
      "description": "Time of the creation of an election in the ISO 8601 format",
      "type": "string",
      "format": "date-time",
      "examples": ["2021-01-01T00:00:00+01:00"]
    },
    "updatedAt": {
      "title": "Updated at",
      "description": "Time of the last update of an election group in the ISO 8601 format",
      "type": "string",
      "format": "date-time",
      "examples": ["2021-01-01T00:00:00+01:00"]
    },
    "publishedAt": {
      "title": "Published at",
      "description": "Time when an election group should be published in the ISO 8601 format",
      "type": "string",
      "format": "date-time",
      "examples": ["2021-01-01T00:00:00+01:00"]
    },
    "title": {
      "title": "Title",
      "description": "Title of an election",
      "type": "string",
      "examples": ["Prezidentské volby 2023"]
    },
    "shortTitle": {
      "title": "shortTitle",
      "description": "Short title of an election with a maximum of 25 characters",
      "type": "string",
      "maxLength": 25,
      "examples": ["Prezidentské 2023"]
    },
    "description": {
      "title": "Description",
      "description": "Description of an election",
      "type": "string",
      "examples": ["Volební kalkulačky pro obě kola prezidentských voleb 2023"]
    },
    "calculatorGroup": {
      "title": "Calculator group",
      "description": "Reference to a calculator group with election calculators",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "./calculator-group.schema.json#/properties/id"
        },
        "key": {
          "$ref": "./calculator-group.schema.json#/properties/key"
        }
      },
      "unevaluatedProperties": false,
      "required": ["id", "key"]
    }
  },
  "properties": {
    "id": {
      "$ref": "#/$defs/id"
    },
    "key": {
      "$ref": "#/$defs/key"
    },
    "createdAt": {
      "$ref": "#/$defs/createdAt"
    },
    "updatedAt": {
      "$ref": "#/$defs/updatedAt"
    },
    "publishedAt": {
      "$ref": "#/$defs/publishedAt"
    },
    "title": {
      "$ref": "#/$defs/title"
    },
    "shortTitle": {
      "$ref": "#/$defs/shortTitle"
    },
    "description": {
      "$ref": "#/$defs/description"
    },
    "calculatorGroup": {
      "$ref": "#/$defs/calculatorGroup"
    },
    "districts": {
      "title": "Ordered list of election districts",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "./district.schema.json"
      }
    },
    "rounds": {
      "title": "Ordered list of election rounds",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "./round.schema.json"
      }
    },
    "votingHours": {
      "title": "Voting hours",
      "description": "One or multiple voting hours for the election",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "./time-period.schema.json"
      }
    }
  },
  "unevaluatedProperties": false,
  "required": [
    "id",
    "key",
    "createdAt",
    "title",
    "shortTitle",
    "calculatorGroup"
  ],
  "dependentSchemas": {
    "rounds": {
      "not": {
        "required": ["votingHours"]
      }
    },
    "votingHours": {
      "not": {
        "required": ["rounds"]
      }
    }
  }
}

=== kalkulacka-one/volebni-kalkulacka-2022/data/instance/kalkulatorizgjedhor.al/kuvendore-2025/election.json
{
  "id": "19cb5123-900d-4f7f-a65f-66d9126b578f",
  "key": "kuvendore-2025",
  "createdAt": "2021-01-01T00:00:00+01:00",
  "title": "Zgjedhjet kuvendore në Shqipëri 2025",
  "shortTitle": "Zgjedhjet kuvendore 2025",
  "calculatorGroup": {
    "id": "70db0917-5a3c-48ff-9f6f-c11eb1d34bd3",
    "key": "kuvendore-2025"
  },
  "votingHours": [
    {
      "start": "2025-02-09T07:00:00+01:00",
      "end": "2025-02-09T17:00:00+01:00"
    }
  ]
}

=== kalkulacka-one/volebni-kalkulacka-2022/data/instance/kalkulatorizgjedhor.org/parlamentare-2025/election.json
{
  "id": "412d0370-7c88-4184-ae7e-befabc4f6ebf",
  "key": "parlamentare-2025",
  "createdAt": "2021-01-01T00:00:00+01:00",
  "title": "Zgjedhjet parlamentare në Kosovë 2025",
  "shortTitle": "Zgjedhjet parlamentare 2025",
  "calculatorGroup": {
    "id": "4ffa236f-5ee0-4d5d-9703-c6a5786d6295",
    "key": "parlamentare-2025"
  },
  "votingHours": [
    {
      "start": "2025-02-09T07:00:00+01:00",
      "end": "2025-02-09T17:00:00+01:00"
    }
  ]
}

=== kalkulacka-one/volebni-kalkulacka-2022/data/instance/wahlrechner.at/wien-wahl-2025/election.json
{
  "id": "aa90257e-8123-46a6-98c6-fd8bccffaa71",
  "key": "wien-wahl-2025",
  "createdAt": "2021-01-01T00:00:00+01:00",
  "title": "Wien-Wahl 2025",
  "shortTitle": "Wien-Wahl 2025",
  "calculatorGroup": {
    "id": "379cac18-71b1-438d-833c-9d0334ed08b5",
    "key": "wien-wahl-2025"
  },
  "votingHours": [
    {
      "start": "2025-04-27T07:00:00+02:00",
      "end": "2025-04-27T17:00:00+02:00"
    }
  ]
}

=== kalkulacka-one/volebni-kalkulacka-2022/data/instance/volebnakalkulacka.sk/nrsr-2023/election.json
{
  "id": "57a09a41-631b-4b40-ac22-b75b8ce14d84",
  "key": "nrsr-2023",
  "createdAt": "2021-01-01T00:00:00+01:00",
  "title": "Voľby do Národnej rady Slovenskej republiky 2023",
  "shortTitle": "Parlamentné voľby 2023",
  "calculatorGroup": {
    "id": "05c64bc5-aa2e-4457-ab30-336f7cf9131b",
    "key": "nrsr-2023"
  },
  "rounds": [
    {
      "number": 0,
      "votingHours": [
        {
          "start": "2023-09-30",
          "end": "2023-09-30"
        }
      ]
    }
  ]
}

=== kalkulacka-one/volebni-kalkulacka-2022/data/instance/testvot.eu/parlamentare-2024/election.json
{
  "id": "7d6fde2b-9e69-4caa-8cdd-906d0685fa09",
  "key": "parlamentare-2024",
  "createdAt": "2024-11-27T11:24:24.870280",
  "title": "Alegeri parlamentare în România 2024",
  "shortTitle": "Alegeri parlamentare în România 2024",
  "calculatorGroup": {
    "id": "33a20a4d-bf6b-4414-80ec-e1e270840c29",
    "key": "parlamentare-2024"
  }
}
