=== kalkulacka-one/volebni-kalkulacka-2022/data/schemas/person.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://www.volebnikalkulacka.cz/data/schemas/person.schema.json",
  "title": "Person",
  "description": "A human being",
  "type": "object",
  "properties": {
    "id": {
      "title": "ID",
      "description": "Unique identifier of a person in the format of UUID",
      "type": "string",
      "format": "uuid",
      "examples": ["5ee570e9-fdc6-4af1-8af5-a5e5589c44a6"]
    },
    "name": {
      "title": "Name",
      "description": "Person's preferred full name",
      "type": "string"
    },
    "familyName": {
      "description": "Family name (last name)",
      "type": "string"
    },
    "givenName": {
      "description": "Given name (first name)",
      "type": "string"
    },
    "additionalName": {
      "description": "Additional name (middle name)",
      "type": "string"
    },
    "honorificPrefix": {
      "description": "Honorifics preceding a person's name",
      "type": "string"
    },
    "honorificSuffix": {
      "description": "Honorifics following a person's name",
      "type": "string"
    },
    "sortName": {
      "description": "A name to use in a lexicographically ordered list",
      "type": "string"
    },
    "alternateNames": {
      "description": "Alternate names to use for example in search",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "memberOf": {
      "title": "Member of",
      "description": "List of organizations a person is a member of",
      "type": "array",
      "minItems": 1,
      "items": {
        "title": "Organization",
        "description": "Reference to an organization",
        "type": "object",
        "properties": {
          "id": {
            "$ref": "./organization.schema.json#/properties/id"
          }
        },
        "unevaluatedProperties": false,
        "required": ["id"]
      }
    }
  },
  "unevaluatedProperties": false,
  "required": ["id"],
  "anyOf": [
    {
      "required": ["name"]
    },
    {
      "required": ["familyName", "givenName"]
    }
  ]
}

=== kalkulacka-one/volebni-kalkulacka-2022/data/instance/volebnakalkulacka.sk/nrsr-2023/inventura-2020-2023/persons.json
[
  {
    "id": "5046d951-ecbd-4d35-b7d3-1ca187e830a9",
    "name": "Martin Beluský",
    "givenName": "Martin",
    "familyName": "Beluský",
    "memberOf": [
      {
        "id": "e7f32688-913f-4aa4-9595-48982de03eea"
      }
    ]
  },
  {
    "id": "d4b55816-a789-42b3-a903-6e45e18a1140",
    "name": "Rastislav Schlosár",
    "givenName": "Rastislav",
    "familyName": "Schlosár",
    "memberOf": [
      {
        "id": "e7f32688-913f-4aa4-9595-48982de03eea"
      }
    ]
  },
  {
    "id": "a672a299-fe16-4c08-8a6c-f6f26eb2c741",
    "name": "Andrej Medvecký",
    "givenName": "Andrej",
    "familyName": "Medvecký",
    "memberOf": [
      {
        "id": "e7f32688-913f-4aa4-9595-48982de03eea"
      }
    ]
  },
  {
    "id": "d850df94-9421-4743-991f-e6205ff38d0d",
    "name": "Stanislav Mizík",
    "givenName": "Stanislav",
    "familyName": "Mizík",
    "memberOf": [
      {
        "id": "e7f32688-913f-4aa4-9595-48982de03eea"
      }
    ]
  },
  {
    "id": "08b7aab2-0dbc-452e-a076-043c21ae6bbb",
    "name": "Peter Krupa",
    "givenName": "Peter",
    "familyName": "Krupa",
    "memberOf": [
      {
        "id": "e7f32688-913f-4aa4-9595-48982de03eea"
      }
    ]
  },
  {
    "id": "10e2c082-a9b5-4671-90df-9e722feb9c29",
    "name": "Marek Kotleba",
    "givenName": "Marek",
    "familyName": "Kotleba",
    "memberOf": [
      {
        "id": "e7f32688-913f-4aa4-9595-48982de03eea"
      }
    ]
  },
  {
    "id": "d601d9eb-a9dc-43d9-938d-c73c97a26250",
    "name": "Magdaléna Sulanová",
    "givenName": "Magdaléna",
    "familyName": "Sulanová",
    "memberOf": [
      {
        "id": "e7f32688-913f-4aa4-9595-48982de03eea"
      }
    ]
  },
  {
    "id": "bb76f803-689f-4b0d-9558-a96a46f3f483",
    "name": "Slavěna Vorobelová",
    "givenName": "Slavěna",
    "familyName": "Vorobelová",
    "memberOf": [
      {
        "id": "1c3dee60-48d4-44a0-930c-852bb44f24eb"
      }
    ]
  },
  {
    "id": "abe410a5-ee24-4823-90b9-a0dd5b9e329a",
    "name": "Milan Mazurek",
    "givenName": "Milan",
    "familyName": "Mazurek",
    "memberOf": [
      {
        "id": "22f5ef54-1908-4dbe-83c2-a9824eac589b"
      }
    ]
  },
  {
    "id": "0f4465a7-f17b-4f5a-9037-bd1f53a7f8bb",
    "name": "Ondrej Ďurica",
    "givenName": "Ondrej",
    "familyName": "Ďurica",
    "memberOf": [
      {
        "id": "22f5ef54-1908-4dbe-83c2-a9824eac589b"
      }
    ]
  },
  {
    "id": "5eeef652-d38f-4929-af3a-7d69104218b8",
    "name": "Eduard Kočiš",
    "givenName": "Eduard",
    "familyName": "Kočiš",
    "memberOf": [
      {
        "id": "22f5ef54-1908-4dbe-83c2-a9824eac589b"
      }
    ]
  },
  {
    "id": "a676bd44-35db-47b3-8871-b914486c4cde",
    "name": "Miroslav Urban",
    "givenName": "Miroslav",
    "familyName": "Urban",
    "memberOf": [
      {
        "id": "22f5ef54-1908-4dbe-83c2-a9824eac589b"
      }
    ]
  },
  {
    "id": "c63176a2-79cc-4947-a51a-f7e130085409",
    "name": "Miroslav Suja",
    "givenName": "Miroslav",
    "familyName": "Suja",
    "memberOf": [
      {
        "id": "22f5ef54-1908-4dbe-83c2-a9824eac589b"
      }
    ]
  },
  {
    "id": "2d77164b-99e7-4628-88e1-925fb647c288",
    "name": "Jozef Šimko",
    "givenName": "Jozef",
    "familyName": "Šimko",
    "memberOf": [
      {
        "id": "c0e67558-eda0-4aca-9908-b93a5ede9008"
      }
    ]
  },
  {
    "id": "2f600134-be6c-4dca-886d-2f9e8c29108a",
    "name": "Štefan Kuffa",
    "givenName": "Štefan",
    "familyName": "Kuffa",
    "memberOf": [
      {
        "id": "a2eb1a71-5c7b-4582-bdc3-04018748d9d6"
      }
    ]
  },
  {
    "id": "78c5ba62-8307-4fb1-884a-231c1be42af1",
    "name": "Filip Kuffa",
    "givenName": "Filip",
    "familyName": "Kuffa",
    "memberOf": [
      {
        "id": "a2eb1a71-5c7b-4582-bdc3-04018748d9d6"
      }
    ]
  },
  {
    "id": "282684b5-3002-44c7-938a-467d027a86da",
    "name": "Tomáš Taraba",
    "givenName": "Tomáš",
    "familyName": "Taraba",
    "memberOf": [
      {
        "id": "a2eb1a71-5c7b-4582-bdc3-04018748d9d6"
      }
    ]
  },
  {
    "id": "1acefce9-fcca-4412-872e-1ec1c387e92e",
    "name": "Ján Mičovský",
    "givenName": "Ján",
    "familyName": "Mičovský",
    "memberOf": [
      {
        "id": "c0cc6ee7-2b0b-4517-9858-3f23c1f391fe"
      }
    ]
  },
  {
    "id": "5150ba5d-7f07-46dd-aa85-8dbee2829d47",
    "name": "Róbert Halák",
    "givenName": "Róbert",
    "familyName": "Halák",
    "memberOf": [
      {
        "id": "c0cc6ee7-2b0b-4517-9858-3f23c1f391fe"
      }
    ]
  },
  {
    "id": "e2d167b1-71f6-428e-ae32-1d1dbb722f6d",
    "name": "Monika Kozelová",
    "givenName": "Monika",
    "familyName": "Kozelová",
    "memberOf": [
      {
        "id": "9530df54-8c39-4b03-88c7-87117b16406f"
      }
    ]
  },
  {
    "id": "537d9bd2-a097-470d-86f3-7f181b6a2537",
    "name": "Anna Mierna",
    "givenName": "Anna",
    "familyName": "Mierna",
    "memberOf": [
      {
        "id": "c0cc6ee7-2b0b-4517-9858-3f23c1f391fe"
      }
    ]
  },
  {
    "id": "5af890d6-9530-42b7-87a2-af07271b4015",
    "name": "Anna Remiášová",
    "givenName": "Anna",
    "familyName": "Remiášová",
    "memberOf": [
      {
        "id": "9530df54-8c39-4b03-88c7-87117b16406f"
      }
    ]
  },
  {
    "id": "c5fc103f-faa8-482d-b9c1-52d270be4d81",
    "name": "Andrej Stančík",
    "givenName": "Andrej",
    "familyName": "Stančík",
    "memberOf": [
      {
        "id": "c0cc6ee7-2b0b-4517-9858-3f23c1f391fe"
      }
    ]
  },
  {
    "id": "e235e041-624a-4089-a714-7cbafbae1bd9",
    "name": "Jaromír Šíbl",
    "givenName": "Jaromír",
    "familyName": "Šíbl",
    "memberOf": [
      {
        "id": "c0cc6ee7-2b0b-4517-9858-3f23c1f391fe"
      }
    ]
  },
  {
    "id": "03e1653f-839e-437a-bf14-c49848c4696a",
    "name": "Jarmila Vaňová",
    "givenName": "Jarmila",
    "familyName": "Vaňová",
    "memberOf": [
      {
        "id": "9530df54-8c39-4b03-88c7-87117b16406f"
      }
    ]
  },
  {
    "id": "a15b9c0d-8d90-4a9d-ac1c-7110b15a9d8d",
    "name": "Kristián Čekovský",
    "givenName": "Kristián",
    "familyName": "Čekovský",
    "memberOf": [
      {
        "id": "c0cc6ee7-2b0b-4517-9858-3f23c1f391fe"
      }
    ]
  },
  {
    "id": "df8b9d33-a113-4ec3-bf96-b0518fbd4de4",
    "name": "Martin Čepček",
    "givenName": "Martin",
    "familyName": "Čepček",
    "memberOf": [
      {
        "id": "9530df54-8c39-4b03-88c7-87117b16406f"
      }
    ]
  },
  {
    "id": "8ee2cb71-1457-431a-962f-12b075404591",
    "name": "Katarína Hatráková",
    "givenName": "Katarína",
    "familyName": "Hatráková",
    "memberOf": [
      {
        "id": "9530df54-8c39-4b03-88c7-87117b16406f"
      }
    ]
  },
  {
    "id": "1f42df25-f048-4e6c-8bab-0df092cbd96d",
    "name": "Ján Krošlák",
    "givenName": "Ján",
    "familyName": "Krošlák",
    "memberOf": [
      {
        "id": "9530df54-8c39-4b03-88c7-87117b16406f"
      }
    ]
  },
  {
    "id": "55f998d5-ab40-4a67-81fa-476b4de81150",
    "name": "Erik Ňarjaš",
    "givenName": "Erik",
    "familyName": "Ňarjaš",
    "memberOf": [
      {
        "id": "9530df54-8c39-4b03-88c7-87117b16406f"
      }
    ]
  },
  {
    "id": "f36717e5-df1c-448a-a214-bf30253e64b1",
    "name": "Anna Záborská",
    "givenName": "Anna",
    "familyName": "Záborská",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
    "id": "3bcd69fd-50de-4dd6-b9d3-3cd540923c31",
    "name": "Martin Fecko",
    "givenName": "Martin",
    "familyName": "Fecko",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
    "id": "c3b033d0-3692-4c1a-bdc5-552ae834be88",
    "name": "Igor Matovič",
    "givenName": "Igor",
    "familyName": "Matovič",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
    "id": "54fd03af-453d-42f2-b40c-8b16796dd7d5",
    "name": "Eva Horváthová",
    "givenName": "Eva",
    "familyName": "Horváthová",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
    "id": "24f31540-c2e1-4484-a4e5-1d852a95798f",
    "name": "Richard Vašečka",
    "givenName": "Richard",
    "familyName": "Vašečka",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
    "id": "18bd1c34-c836-45ba-8e08-e6a9e74d2910",
    "name": "Marek Krajčí",
    "givenName": "Marek",
    "familyName": "Krajčí",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
    "id": "2fd13bd0-7e9f-43cb-adf6-5834f93183f0",
    "name": "Gábor Grendel",
    "givenName": "Gábor",
    "familyName": "Grendel",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
    "id": "0a0af936-a19c-4e6f-8daf-997c98366799",
    "name": "Anna Andrejuvová",
    "givenName": "Anna",
    "familyName": "Andrejuvová",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
    "id": "88d93598-9409-4a79-b6e0-bc90e71d8217",
    "name": "Martina Brisudová",
    "givenName": "Martina",
    "familyName": "Brisudová",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
    "id": "05934a39-6281-4e77-8c3b-1c52b1e255ea",
    "name": "Peter Dobeš",
    "givenName": "Peter",
    "familyName": "Dobeš",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
    "id": "9888385e-2f69-41ed-a865-acae9bc00c20",
    "name": "Lucia Drábiková",
    "givenName": "Lucia",
    "familyName": "Drábiková",
    "memberOf": [
      {
        "id": "9530df54-8c39-4b03-88c7-87117b16406f"
      }
    ]
  },
  {
    "id": "e28f3f6e-ee30-43ab-9f40-069b54f7ad6c",
    "name": "Dominik Drdul",
    "givenName": "Dominik",
    "familyName": "Drdul",
    "memberOf": [
      {
        "id": "869e4c1b-6635-4ff0-b0ac-b6eb1bd67b04"
      }
    ]
  },
  {
