=== kalkulacka-one/volebni-kalkulacka-2022/data/schemas/question.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://www.volebnikalkulacka.cz/data/schemas/question.schema.json",
  "title": "Question",
  "description": "Question for a calculator",
  "type": "object",
  "properties": {
    "id": {
      "title": "ID",
      "description": "Unique identifier of a question in the format of UUID",
      "type": "string",
      "format": "uuid",
      "examples": ["51115be7-246a-4f07-baf7-247ee81fde36"]
    },
    "title": {
      "title": "Title",
      "description": "Title of a question",
      "type": "string",
      "examples": ["Zrušení Senátu"]
    },
    "statement": {
      "title": "Statement",
      "description": "A statment to agree or disagree with, should not be phrased as a question with question mark",
      "type": "string",
      "examples": ["Senát by se měl zrušit"]
    },
    "detail": {
      "title": "Detail",
      "description": "A detailed description or an explanation of a question",
      "type": "string",
      "examples": [
        "Senát by se měl zrušit, protože je zbytečný a jeho činnost je nákladná."
      ]
    },
    "tags": {
      "$ref": "./tags.schema.json"
    }
  },
  "unevaluatedProperties": false,
  "required": ["id", "title", "statement"]
}

=== kalkulacka-one/volebni-kalkulacka-2022/data/instance/kalkulatorizgjedhor.al/kuvendore-2025/kalkulatori/questions.json
[
  {
    "id": "c29e1c87-c093-4cd7-b6c7-5a1dfddcacda",
    "title": "Ndalimi i TikTok-ut",
    "statement": "A duhet Shqiëpria të vazhdojë me ndalimin e rrjetit social TikTok?",
    "detail": "",
    "tags": []
  },
  {
    "id": "bee382c9-cc9f-42ee-9c78-219c99b6834d",
    "title": "Orari 7-Orësh",
    "statement": "A duhet Shqiëpria të adoptojë orarin zyrtar të punës me 7 orë punë në ditë (09:00 – 16:00)?",
    "detail": "",
    "tags": []
  },
  {
    "id": "66066811-fde6-4655-bb57-ade9f6f87360",
    "title": "Drekë Falas për Nxënësit",
    "statement": "A duhet Shqipëria të ofrojë drekën falas për nxënësit në shkolla?",
    "detail": "",
    "tags": []
  },
  {
    "id": "5d0713c6-8885-4a17-a250-45c5af67505d",
    "title": "Taksë e Sheshtë",
    "statement": "A duhet që Shqipëria të vendosi taksën e sheshtë ndaj të ardhurave?",
    "detail": "",
    "tags": []
  },
  {
    "id": "e2434058-469f-4c56-8f2a-83532d0133e5",
    "title": "Taksimi ndaj të Pasurve",
    "statement": "A duhet që Shqipëria të rrisë nivelin e taksimit ndaj të pasurve?",
    "detail": "",
    "tags": []
  },
  {
    "id": "ce628994-51c5-45e8-934d-c858e202bf10",
    "title": "Formula për Pensionet",
    "statement": "A duhet Shqipëria të përcaktojë një formulë për rritjen e pensioneve?",
    "detail": "",
    "tags": []
  },
  {
    "id": "c04416be-daf6-4c45-9cb0-46a09dd6522c",
    "title": "Kartë Konsumatori",
    "statement": "A duhet Shqipëria të krijojë një kartë konsumatori për shtresat vulnerabël?",
    "detail": "",
    "tags": []
  },
  {
    "id": "2ae28d53-1cb6-4c25-afe3-1d73bf8f4587",
    "title": "Kredi për të Rinj",
    "statement": "A duhet Shqipëria të ofrojë kredi të buta për banesë dhe biznes të vogël për të rinjtë nën 30 vjeç?",
    "detail": "",
    "tags": []
  },
  {
    "id": "e7f4de84-21f1-41b6-9812-8e250450b876",
    "title": "Rivlerësimi i Kontratave PPP",
    "statement": "A duhet Shqipëria të bëjë një rivlerësim të të gjitha kontratave publiek të dhëna me partneritet public-privat?",
    "detail": "",
    "tags": []
  },
  {
    "id": "4631a215-6b77-4ee9-a498-1aad8177de65",
    "title": "Ndalimi i Offshore në Tendera",
    "statement": "A duhet Shqipëria të ndalojë pjesëmarrjen e kompanive offshore me pronarë të fshehur në tendera publikë?",
    "detail": "",
    "tags": []
  },
  {
    "id": "554ae22a-7cc3-40d6-a549-5bc1c2d169f1",
    "title": "AI në Prokurimet Publike",
    "statement": "A duhet Shqipëria të përfshijë Inteligjencën Artificiale për prokurimet publike?",
    "detail": "",
    "tags": []
  },
  {
    "id": "3381db85-bf39-4b03-890c-9552615c03d6",
    "title": "Rikonceptimi i Hartës Gjyqësore",
    "statement": "A duhet Shqipëria të rikonceptojë hartën gjyqësore?",
    "detail": "",
    "tags": []
  },
  {
    "id": "4ce76259-cf60-46fa-af34-aac4d79c416c",
    "title": "Fund Ligjit të Investimeve Strategjike",
    "statement": "A duhet Shqipëria t’i japë fund ligjit të investimeve strategjike?",
    "detail": "",
    "tags": []
  },
  {
    "id": "9a96cf86-a8ac-4394-981f-4a83268f8696",
    "title": "Rindërtimi i Rafinerisë",
    "statement": "A duhet Shqipëria të rindërtojë nëj rafineri për përpunimin e naftës që del nga nëntoka Shqipëtare?",
    "detail": "",
    "tags": []
  },
  {
    "id": "4ec6a812-b8c9-4c68-8ed1-fe100c5ea0f6",
    "title": "Subvencione për Fermerët",
    "statement": "A duhet Shqipëria të parashikojë 100 milionë euro subvencione në vit për fermerët dhe 50 milionë euro për infrastrukturë agrokulturore?",
    "detail": "",
    "tags": []
  },
  {
    "id": "952a010e-d053-4e6c-af25-96afbc03147e",
    "title": "Taksë për Apartamentet e Shumta",
    "statement": "A duhet Shqipëria të vendosë taksë progressive për pronësinë e apartamenteve të treta, të katërta e kështu me rradhë?",
    "detail": "",
    "tags": []
  },
  {
    "id": "340a8a26-e72d-437b-8eea-cac27102c710",
    "title": "Çmim i Diferencuar i Energjisë",
    "statement": "A duhet Shqipëria të përdorë fasha të ndryshme të ccmimit të energjisë bazuar ën konsum?",
    "detail": "",
    "tags": []
  },
  {
    "id": "bc6b1115-d6b7-4bb8-b4da-e7d5682697dd",
    "title": "Ndalimi i Monopolit Mediatik",
    "statement": "A duhet Shqipëria të ndalojë pronësinë 100% të mediave nga një person apo famile?",
    "detail": "",
    "tags": []
  },
  {
    "id": "9895b179-f59a-4c31-bf23-63a68d9ffbea",
    "title": "Arsim Falas deri në Master",
    "statement": "A duhet Shqipëria të ofrojë arsim falas deri në nivelin master?",
    "detail": "",
    "tags": []
  },
  {
    "id": "c1c11b6f-6257-40f5-adc0-c5717d6a9896",
    "title": "Rritja e Pagës së Mësuesve",
    "statement": "A duhet Shqipëria të rrisë me 25% pagën e mësuesve ccdo vit për 4 vite rradhazi?",
    "detail": "",
    "tags": []
  },
  {
    "id": "ce10c562-f452-44ca-8c07-7e70ca1e58e0",
    "title": "2 Miliardë për Bizneset",
    "statement": "A duhet shteti të ofroje 2 miliardë euro si kredi dhe garanci përbizneset për rritjen e investimeve dhe prodhimin vendas?",
    "detail": "",
    "tags": []
  },
  {
    "id": "84f02656-69c3-4631-9f6c-8e938b271714",
    "title": "Pa Kontrolle për Bizneset e Reja",
    "statement": "A duhet Shqipëria të ndalojë kontrollet shtetërore tek bizneset e reja për 3 vitet e para?",
    "detail": "",
    "tags": []
  },
  {
    "id": "9e28509c-a4f1-4539-8289-ac80f92c9c2a",
    "title": "Bashkëpronësi Industriale",
    "statement": "A duhet shteti të jetë bashkëpronar me % më të lartë në fushat kryesore të industrisë?",
    "detail": "",
    "tags": []
  },
  {
    "id": "b1f209f1-a4fb-4b63-b55b-ee400df114e5",
    "title": "Forcimi i Kodit për Sigurinë Ushqimore",
    "statement": "A duhet Shqipëria të forcojë Kodin Penal për shkelje të sigurisë ushqimore deri në masën e konfiskimit të biznesit?",
    "detail": "",
    "tags": []
  },
  {
    "id": "b7458383-f428-4baa-8b77-16815c908253",
    "title": "Praktika të Pagura për Studentët",
    "statement": "A duhet Shqipëria të ofrojë praktika pune të paguara për studentët?",
    "detail": "",
    "tags": []
  },
  {
    "id": "6ddddc0b-c16f-495f-88a1-d638ad96f6ec",
    "title": "Statusi i Minatorit",
    "statement": "A duhet Shqipëria të miratojë statusin e minatorit?",
    "detail": "",
    "tags": []
  },
  {
    "id": "25da7218-54d7-441a-a3d5-1babab4a244d",
    "title": "600€ për Fëmijët",
    "statement": "A duhet Shqipëria të japë 600 euro në vit për çdo fëmijë deri në 14 vjeç për familjet me të ardhura nën mesatare?",
    "detail": "",
    "tags": []
  },
  {
    "id": "61ab1f96-cc0a-44d2-abeb-d677da765432",
    "title": "Ligji për Referendumet",
    "statement": "A duhet Shqipëria të miratojë ligjin për referendumet për të lejuar qytetarët të vendosin drejtpërdrejt për ccështje të caktuara?",
    "detail": "",
    "tags": []
  },
  {
    "id": "0b95d60e-3a33-4dd5-b2e0-2f818d94e4b7",
    "title": "Transport Publik për Nxënësit",
    "statement": "A duhet Shqipëria të krijojë një kompani shtetërore të transportit publik për shkollat për të ccuar në shkollë dhe në shtëpi nxënësit?",
    "detail": "",
    "tags": []
  },
  {
    "id": "b9fb1709-6358-4adf-85ad-dc9ec7a55e29",
    "title": "Adoptimi i Euros",
    "statement": "A duhet Shqipëria të adoptojë euron si monedhën e saj duke hequr lekun?",
    "detail": "",
    "tags": []
  }
]

=== kalkulacka-one/volebni-kalkulacka-2022/data/instance/volebnakalkulacka.sk/nrsr-2023/pre-mladych/questions.json
[
  {
    "id": "db7ac818-effe-4bc7-ba9c-1798e6649da7",
    "title": "Slovensko a klimatické zmeny",
    "statement": "Slovensko má robiť proti klimatickým zmenám viac ako teraz.",
    "tags": [
      "životné prostredie"
    ]
  },
  {
    "id": "e1850f01-4023-4bc2-bc01-e0d8853f0e2b",
    "title": "Vyššia daň za prázdne byty",
    "statement": "Dlhodobo prázdne byty by mali byť viac zdanené.",
    "tags": [
      "bývanie"
    ]
  },
  {
    "id": "f3e7a5b8-e37a-4869-9674-22c2cff4cb82",
    "title": "Slovensko mimo EU",
    "statement": "Slovensko by malo vystúpiť z EÚ.",
    "tags": [
      "diplomácia"
    ]
  },
  {
    "id": "66fa5905-6513-4d80-bbb6-7897f0c3b465",
    "title": "Školné na VŠ",
    "statement": "Na verejných vysokých školách by sa malo platiť školné.",
    "tags": [
      "vzdelávanie"
    ]
  },
  {
    "id": "7d30b158-c981-4838-a3f8-ee5eeac86d18",
    "title": "Hlasovanie cez internet",
    "statement": "Mala by sa zaviesť možnosť voliť cez internet.",
    "tags": [
      "demokrácia"
    ]
  },
  {
    "id": "5b15f407-fd1b-4fbe-9a20-bf975a126499",
    "title": "Zákaz automatického rozpoznávania tváre",
    "statement": "Používanie systémov automatického rozpoznávania tváre na verejných miestach by malo byť zakázané.",
    "detail": "Systémy na rozpoznávanie tváre využívajúce umelú inteligenciu môžu okrem iného prostredníctvom kamier sledovať jednotlivých ľudí na verejnosti.",
    "tags": [
      "ochrana súkromia"
    ]
  },
  {
    "id": "07225905-b95c-4e39-afaf-c51d0a631453",
    "title": "Legálne pestovanie konope",
    "statement": "Pestovanie konope (marihuany) na osobné použitie by malo byť legálne.",
    "tags": [
      "právo"
    ]
  },
  {
    "id": "744b7d88-fcc9-40cd-96b0-1f33b53ca6f2",
    "title": "Zákaz interrupcie",
    "statement": "Interrupcia by mala byť zakázaná až na výnimočné prípady, ako je znásilnenie alebo ohrozenie života matky.",
    "tags": [
      "rodina"
    ]
  },
  {
    "id": "0a915a97-2c29-4b3c-afe4-3b7510bcbfe3",
    "title": "Registrované partnerstvo",
    "statement": "Homosexuálne páry by mali mať možnost uzavrieť registrované partnerstvo.",
    "tags": [
      "rodina"
    ]
  },
  {
    "id": "45de98e3-1e94-4366-8f46-8378e3e69268",
    "title": "Výber pohlavia dieťaťa",
    "statement": "Rodičia v SR by mali mať možnosť vybrať si pohlavie dieťaťa pri umelom oplodnení.",
    "detail": "Slovensko podpísalo Oviedsku zmluvu o ľudských právach a biomedicíne. Táto medzinárodná zmluva okrem iného zakazuje výber pohlavia dieťaťa pri umelom oplodnení (s výnimkou niektorých preukázaných dedičných porúch). Výber pohlavia dieťaťa je nezákonný vo väčšine krajín sveta s výnimkou USA.",
    "tags": [
      "rodina"
    ]
  },
  {
    "id": "6f5dc0ee-308f-4799-b96e-2e05ca058041",
    "title": "Zodpovednosť sociálnych sietí",
    "statement": "Sociálne siete by mali byť zodpovedné za obsah, ktorý sprístupňujú.",
    "detail": "Veľké sociálne siete ako Facebook alebo Youtube sú dnes koncipované skôr ako nástenky: zodpovednosť (vrátane trestnoprávnej) za zverejnený obsah nesie predovšetkým osoba, ktorá obsah na sieť nahrala. Naopak, napríklad médiá sú zodpovedné za každý obsah, ktorý zverejnia.",
    "tags": [
      "média"
    ]
  },
  {
    "id": "4639ba79-463e-4c19-974e-f0509ff92aaa",
    "title": "Zvýšenie dane z alkoholu",
    "statement": "Spotrebná daň z alkoholu by sa mala zvýšiť.",
    "tags": [
      "ekonomika"
    ]
  },
  {
    "id": "f3482887-4800-4683-9afb-fb6dbb37e73e",
    "title": "Maloletí (zákaz reklamy)",
    "statement": "Reklama zameraná na deti by mala byť zakázaná.",
    "tags": [
      "spoločnosť"
    ]
  },
  {
    "id": "a6ba8152-b7bf-4c20-a337-d80c2dad9347",
    "title": "Dostupnosť psychoterapie",
    "statement": "Psychoterapia by mala byť štandardne hradená zo zdravotného poistenia.",
    "detail": "Dostupnosť psychoterapie je na Slovensku vo všeobecnosti nízka, dopyt je vysoký a čakacie lehoty sú neraz dlhé. A jej ceny určuje aj trh. Je možné absolvovať psychoterapiu hradenú z poistenia, ak ide o zdravotne indikovaný výkon – teda že pacient má diagnózu, ktorú možno efektívne ovplyvniť psychoterapiou.",
    "tags": [
      "zdravotníctvo"
    ]
  },
  {
    "id": "992f35be-e51e-4baa-a4f9-a009a9de5141",
    "title": "Očkovanie dobrovoľné",
    "statement": "Očkovanie by malo byť vždy dobrovoľné.",
    "tags": [
      "zdravotníctvo"
    ]
  },
  {
    "id": "f110a370-bf2b-41a9-a790-dc9733e2ebd5",
    "title": "Lekárske VŠ",
    "statement": "Absolventi lekárskych VŠ majú mať povinnosť niekoľko rokov pracovať na Slovensku, inak by museli doplatiť školné.",
    "tags": [
      "vzdelávanie"
    ]
  },
  {
    "id": "5939bbe8-70d8-43c5-8478-b6e5c2584f66",
    "title": "Vyššia DPH na škodlivé potraviny",
    "statement": "Zdraviu škodlivé potraviny (napr. malinovky, cukrovinky či hranolky) by mali mať vyššiu sadzbu DPH.",
    "tags": [
      "zdravotníctvo"
    ]
  },
  {
    "id": "8bcaec5d-a64b-40b3-b43d-c810c94d2c10",
    "title": "Ratifikácia Istanbulského dohovora",
    "statement": "Slovensko by malo ratifikovať Istanbulský dohovor.",
    "detail": "Ide o Dohovor Rady Európy o predchádzaní násiliu na ženách a domácemu násiliu. Okrem Slovenska zmluvu neratifikovali Česká republika, Maďarsko, Bulharsko, Litva, Lotyšsko a Arménsko. Azerbajdžan ju ani nepodpísal.",
    "tags": [
      "spoločnosť"
    ]
  },
  {
    "id": "d755713e-24df-4a1d-a606-7430815c4f8a",
    "title": "Podpora jadrovej energetiky",
    "statement": "Jadrová energetika by mala byť podporovaná z verejných zdrojov.",
    "detail": "Viac ako polovicu elektrickej energie (55 %) vyrába Slovensko v jadrových elektrárňach. Jedinou ďalšou krajinou EÚ s viac ako polovicou elektriny vyrobenej v jadrových elektrárňach je Francúzsko (67 % všetkej elektriny vyrobenej v krajine). V Nemecku a Rakúsku je to 0 %, v Holandsku 3 %. V Česku 37 %, v Maďarsku 46 %. Vo Španielsku 22 %, Švédsku 30 %, Fínsku 34 %.",
    "tags": [
      "životné prostredie"
    ]
  },
  {
    "id": "5cf42b4e-c3af-4711-a665-404b7185b5e0",
    "title": "Národné parky - rozšírenie bezzásahových zón",
    "statement": "Súhlasím s rozšírením bezzásahových zón s najvyšším stupňom ochrany v národných parkoch.",
    "detail": "Slovensko má deväť národných parkov a tretina z nich je dnes zazónovaná (Muránska planina, Slovenský raj, Pieninský národný park). Podľa súčasne platného zákona mali bezzásahové zóny dosahovať 50 percent plochy parkov. V roke 2011 bol plán, že bezzásahové zóny budú v roce 2030 zaberať 3/4 plochy parkov.",
    "tags": [
      "životné prostredie"
    ]
  },
  {
    "id": "bcf92117-efa2-435a-b459-9ed2f5e3d87e",
    "title": "Dvojí štátne občianstvo",
    "statement": "Súhlasím s tým, aby si ľudia, ktorí prijali občianstvo iného štátu, mohli nechať slovenské občianstvo.",
    "tags": [
      "demokrácia"
    ]
  },
  {
    "id": "b12c4cf4-0c5c-43b2-899b-d1b778e442f3",
    "title": "Kolonizácia Marsu",
    "statement": "Slovensko by sa malo viac zapojiť do úsilia o kolonizáciu Marsu.",
    "detail": "V súčasnosti sú na Marse 3 robotické prieskumné vozidlá (2 x NASA, 1 x Čína). 7 satelitov obieha okolo Marsu, z toho 2 európske. USA plánujú do 10 rokov letieť na Mars s ľuďmi a podobné programy majú aj Spojené arabské emiráty a Čína. Fyzik Stephen Hawking v roku 2017 predpovedal, že ľudstvo si musí v priebehu niekoľkých storočí nájsť domov mimo Zeme kvôli rizikám, ako sú zmena klímy, znečistenie, pandémie spôsobené novým vírusom, nezvládnutá umelá inteligencia a rast populácie.",
    "tags": [
      "spoločnosť"
    ]
  },
  {
    "id": "2a97a71f-a594-430b-8b2d-ee71fdd9a114",
    "title": "Skrátenie pracovnej doby",
    "statement": "Podporujem prijatie zákona, ktorý skráti pracovný čas zamestnancov.",
    "detail": "Všeobecne platí, že pracovný čas zamestnanca je najviac 40 hodín týždenne. Priemerný týždenný pracovný čas zamestnanca vrátane práce nadčas nesmie prekročiť 48 hodín.",
    "tags": [
      "ekonomika"
    ]
  },
  {
    "id": "562c7de1-6e2b-4a59-8f23-beb88b0f0a04",
    "title": "Slovensko mimo NATO",
    "statement": "Slovensko by malo vystúpiť z NATO.",
    "tags": [
      "diplomácia"
    ]
  },
  {
    "id": "cdd039f1-1bbf-4e25-a935-5ad2e328c601",
    "title": "Regulačný lov medveďov",
    "statement": "Ste za regulačný lov medveďov?",
    "detail": "Podľa odborníkov medveď hnedý stráca svoju plachosť. Časť politikov sľubuje likvidáciu \"ľudožrúta\" a poľovníci tvrdia, že lov je jediným spôsobom, ako útoky medveďov na ľudí zastaviť. Podľa kritikov viedol v minulosti povolený lov k odstrelu medveďov, ktoré neútočili na ľudí a slúžil najmä na zábavu a biznis. Podľa dostupných údajov sa počet medveďov za posledných 20 rokov nezvýšil.",
    "tags": [
      "životné prostredie"
    ]
  }
]
